=== walter-weinmann/repsi-tool/REPSI_Tool_02.00/in/dtd/script_file.dtd
<?xml version='1.0' encoding='utf-8'?>
<!-- DTD for a master database manipulation session. -->
<!ELEMENT Session (DDL_Statement*, DML_Statement*)>
<!ELEMENT DDL_Statement (#PCDATA)>
<!ELEMENT DML_Statement (#PCDATA)>

=== walter-weinmann/repsi-tool/REPSI_Tool_02.00_Development/in/halevy_test_db_schema_drop.xml
<!DOCTYPE Session SYSTEM "dtd/script_file.dtd" >
<Session>
<!-- ===========================================================================
     Table with referential integrity at the next following level
==== ======================================================================= -->
   <DDL_Statement>DROP VIEW VHY_GRADUATE16 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE15 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE14 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE13 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE12 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE11 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE10 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE09 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE08 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE07 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE06 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE05 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE04 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE03 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE02 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE01 CASCADE;</DDL_Statement>

   <DDL_Statement>DROP VIEW VHY_GRADUATE2 CASCADE;</DDL_Statement>
   <DDL_Statement>DROP VIEW VHY_GRADUATE1 CASCADE;</DDL_Statement>

   <DDL_Statement>DROP VIEW VHY_GRADUATE CASCADE;</DDL_Statement>

<!-- ===========================================================================
     Table with referential integrity at the next following level
==== ======================================================================= -->
   <DDL_Statement>DROP TABLE THY_ADVISES CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_REGISTERED CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_MAJOR CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_TEACHES CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_WORKSIN CASCADE;</DDL_Statement>

<!-- ===========================================================================
     Table with referential integrity at the next following level
==== ======================================================================= -->
   <DDL_Statement>DROP TABLE THY_COURSE CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_DEPT CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_EVALUATION CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_PROF CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE THY_QUARTER CASCADE;</DDL_Statement>

</Session>

=== walter-weinmann/repsi-tool/REPSI_Tool_02.00_Development/in/std_master_db_schema_drop.xml
<!DOCTYPE Session SYSTEM "dtd/script_file.dtd" >
<Session>
<!-- ===========================================================================
     Table with referential integrity at the next following level
==== ======================================================================= -->
   <DDL_Statement>DROP TABLE TMD_CALIBRATION_STATISTIC CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TRIAL_RUN_PROTOCOL CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TRIAL_RUN_ACTION CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TRIAL_RUN CASCADE;</DDL_Statement>

<!-- ===========================================================================
     Table with referential integrity at the next following level
==== ======================================================================= -->
   <DDL_Statement>DROP TABLE TMD_CALIBRATION CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TEST_TABLE_DDL CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_DATABASE_INSTANCE CASCADE;</DDL_Statement>

<!-- ===========================================================================
     Table with referential integrity at the next following level
==== ======================================================================= -->
   <DDL_Statement>DROP TABLE TMD_TEST_TABLE CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TEST_SUITE_ACTION CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TEST_QUERY_PAIR CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_PROCESSOR CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_OPERATING_SYSTEM CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_DATABASE_SYSTEM CASCADE;</DDL_Statement>

<!-- ===========================================================================
     Table without referential integrity
==== ======================================================================= -->
   <DDL_Statement>DROP TABLE TMD_VENDOR CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TRIAL_RUN_STATUS CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TEST_SUITE_OPERATION CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_TEST_SUITE CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_SQL_SYNTAX CASCADE;</DDL_Statement>

   <DDL_Statement>DROP TABLE TMD_PATTERN_SQL_IDIOM CASCADE;</DDL_Statement>

<!-- ===========================================================================
     Types
==== ======================================================================= -->
   <DDL_Statement>DROP TYPE CT_MD_READINGS;</DDL_Statement>

</Session>
